### ISSUE TITLE
Add a signup module

### ISSUE THREAD

**Issue by michbarsinai** [theImprovery/PSPS#19]
Allow a signup flow, where future users:
1. Submit their email (invitation record, same as in forgot password and invite request. Also can maybe consolidate or reuse these)
2. get a link to continue the signup process (select username, fill in data)
3. when a user is created, the system deletes the invitation record.

⚠️ The signup can be turned off using  a setting, e.g. `AllowSignup=false` (`null` for this setting means `true`).

**Comment by MorVilozni** [comment]
d09ddeb26f8e76d7566ea6b39d33fb0b92a5e150
